root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -gcflags \"all=-N -l\" -o ./tmp/main ."
bin = "tmp/main"
#full_bin = "APP_ENV=dev APP_USER=air dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec ./tmp/main 80"
full_bin = "APP_ENV=dev APP_USER=air ./tmp/main 80"

include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]
include_dir = []
exclude_file = []
exclude_regex = ["_test.go"]
exclude_symlink = true
follow_symlink = true
log = "air.log"
delay = 1000
stop_op_error = true
send_interrupt = false
kill_delay = 500

[log]
time = false

[color]
main = "megenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true